### PR TITLE
Merged with Jekyll-Asciidoc-Quickstart

### PR DESCRIPTION
**Pull request by johncarl81**
To preview run:
`$ jekyll serve`

To publish using Travis you'll need to turn Travis on, add github key:
`$ travis encrypt GH_TOKEN=<INSERT_TOKEN} --add env.global`
And push to repository.  Travis will do the rest.

Let me know if you have any problems.

### CODE REVIEW

**Comment by johncarl81** [comment]
Oh, and I tried to copy your initial style, but, as always, it may need some tweaking.

Also, I couldn't figure out how to render a table of contents.  Maybe @mojavelinux could help with this?

**Comment by johncarl81** [comment]
I couldn't help myself, I had to deploy it myself.  

You'll find a previous for the time being here: http://johncarl81.github.io/Pinball_Arcade_Users_Guide_Android/

**Comment by jaredmorgs** [comment]
Hey @johncarl81 

Thanks for this PR. You've saved me a stack of time with the work.

I've just worked out what JAQ is: Jekyll AsciiDoc Quickstart. Man, you wouldn't believe the strange Google Searches I've performed this morning :stuck_out_tongue: 

I know @mojavelinux is slammed at the moment, and I really need that TOC in the doc. I'm gonna sit on this PR a bit longer and use the time to look into the tech more.

I wonder if something exists that would let you host multiple docs on the one JAQ page, with a navigation menu? Maybe using Categories I could use the category cloud as some sort of navigation, and just append the name of the doc as a category? Sounds a bit "hacky"...

I think there might be some other guides that I'll be writing, and it would be good to switch the domain to something more generic like jaredmorgs.github.io/docs and have a navigation to other docs. I'd imagine I'd need to push the docs in different folders so they would have different root .adoc files.

**Comment by johncarl81** [comment]
That made me laugh today.. I was picturing what you would find when
searching for JAQ.

I've manually created a TOC in my transfuse site (see Documentation
dropdown): http://androidtransfuse.org/ which exists in the html layout.
I'd love to know how to generate a TOC, maybe I could get rid of the manual
html layout.  I'm not sure about putting multiple rendered documents in one
page, but Dan might know.

Sounds great.  I'm liking the idea of targeting documentation websites more
and more with JAQ.  I think it makes a lot of sense.  Are you on board with
this idea?

Let me know if you have any more thoughts.  Thanks.

John

**Comment by jaredmorgs** [comment]
Yep, I'm totally on board with the idea.

I do think HubPress has overshadowed the efforts put into JAQ, but that's a
good thing if you think about it.

We certainly don't need to throw the baby out with the bathwater. Creating
a light docs site for small projects would be a pretty amazing thing to do,
and there isn't anything out there at the moment you can just "fork and
write". Even if you need to configure travis initially, that's going to be
pretty fine for most people.

Should we create a clean break for the repo and clean out anything we don't
need.

Should we do this up in asciidoctor GitHub?

**Comment by johncarl81** [comment]
Cool.

I think a clean break is unnecessary.  I think the only thing required is
some updates to the README, an update to the default look and feel and
maybe some more content tweaks.  What do you think?

John

**Comment by johncarl81** [comment]
FYI: http://jekyllrb.com/docs/plugins/
In particular: https://github.com/dafi/jekyll-toc-generator
I wonder if these will work with the Asciidoc rendered content.

**Comment by jaredmorgs** [comment]
That'd be worth a short, for sure.

**Comment by johncarl81** [comment]
FYI, I was able to get the TOC working through javascript: https://github.com/ghiculescu/jekyll-table-of-contents

**Comment by jaredmorgs** [comment]
Just checked out http://johncarl81.github.io/Pinball_Arcade_Users_Guide_Android/ @johncarl81 

That TOC actually looks better than the default AsciiDoctor one. :+1: Would that be compatible with the Travis CI approach, or would folks need to build that on a computer to get that TOC to generate?

**Comment by jaredmorgs** [comment]
I'm going to follow the Readme now and see if I can get this thing going from Travis' perspective

**Comment by johncarl81** [comment]
Sweet.  Yes, it's completely compatible with eh Travis CI approach... it's javascript based so its completely client side and will be self-maintaining.

**Comment by jaredmorgs** [comment]
Boom! Fixed it!

. default.html

```
    <link rel="stylesheet" href="{{page.root}}css/font-awesome.css"/>
```

Adding that one line made the icons return!

Should we add this to the JAQ master on github at this stage?

**Comment by johncarl81** [comment]
Yes.  Can you put together a PR?

**Comment by jaredmorgs** [comment]
Trying to work out what I cherrypick out of the work you did on the repo.
Create a PR branch and strip out all the .adoc document files, then create
a PR from our (mostly your) combined effort?

How would I strip out that travis key info?

Clearly this is the first time I've ever pushed something like this back to
the upstream with mixed content. Just want to make sure I do it right. :D

**Comment by johncarl81** [comment]
I would just cherry pick f1bf8ae4fa3d0ca65f6076d1da0b542ea824a13e and any ohter supporting commits / files.  Don't worry, I'm forgiving :smile:

**Comment by mojavelinux** [comment]
JAQ is looking really looking solid!!

There is a much, much simpler way to get a Table of Contents generated. Just use the block macro toc.

```
:toc: macro

toc::[]
```

Voila! Table of contents. No JavaScript.

It's true that you have to manually load Font Awesome. This is one of the things you get for free rendering a standalone AsciiDoc document, but you lose when rendering an embeddable document (same for the sidebar toc). That's because we lose the outer frame template that the HTML5 backend gives us when rendering to embeddable HTML.

Btw, I also recommend separating include directives that are including discrete section content by blank lines so that you don't get content inadvertently merging. This is a best practice.

```
include::/docs/Introduction.adoc[]

include::/docs/Settings_Menu.adoc[]

include::/docs/Table_Menu.adoc[]

include::/docs/Google_Play_Services.adoc[]

include::/docs/Launch_Button.adoc[]

include::/docs/Controller_Settings.adoc[]

include::/docs/Android_Sound_Delay.adoc[]
```

**Comment by johncarl81** [comment]
Nice, much cleaner than the Javascript solution.  I knew @mojavelinux would have the answer.

I'm loving where we've gone with JAQ (even the name is cool!).  Since the advent of HubPress we decided to focus on project documentation rather than a personal blog.  Since then I've based my project sites (androidtransfuse.org and parceler.org) on it.

**Comment by jaredmorgs** [comment]
Thanks for all these tips, Dan!

I'll roll these in tonight.

What I think could be awesome is to somehow created "Jump To Top" links at
the end of each section.

And having the ability for JAQ to handle multiple nested docs and create a
dynamic TOC for the nested discreet docs would be an amazing GET for small
teams and small companies wanting a docs hub.

I am at a loss how to do it automatically.

We should get the JAQ on the staticgen.org site as well. HubPress is up
there. ;)

**Comment by mojavelinux** [comment]
Hey @mojavelinux and apologies for taking so damn long to respond. Too much other stuff happening for me at the moment.

> Documentation portals tend to have a lot more customization requirements, which perfectly justifies the use of Jekyll. It will be fascinating to watch both projects evolve and build on the other's discoveries as well.

Something I'm really conscious of is breaking the "Easy to Set Up" aspects of JAQ. But I understand that the main goal of JAQ is giving folks an easy way to get started with Asciidoctor, then where they evolve JAQ from there is up to them.

> > What I think could be awesome is to somehow created "Jump To Top" links at the end of each section.
> 
> I think that would be a very nice addition for Asciidoctor core. Having said that, Jekyll gives us the perfect opportunity to weave that in today using extensions. If you use a Treeprocessor extension, you can grab each section and append an additional paragraph block to the end that includes a jump to top section. Another approach is to use a floating jump to top using some CSS magic like we've seen on many sites such as the enfold theme for WordPress (scroll down on the following page http://www.kriesi.at/themes/enfold/blog/).

Again, I want any changes folks add to still be processable with TravisCI. My vision for JAQ is to still allow folks to set it up once then commit changes from any device and hand of the build to Travis.

> > And having the ability for JAQ to handle multiple nested docs and create a dynamic TOC for the nested discreet docs would be an amazing GET for small teams and small companies wanting a docs hub.
> 
> Seems like this should become an issue so we can dive into the requirements. Are you thinking something like OpenShift's new documentation portal? (see http://docs.openshift.org/latest/welcome/index.html). Or something else? Perhaps you can clarify in the process of filing an issue.

I'll get onto this now.

Thanks again to the Asciidoctor team at large for being so generous with your time and expertise. It makes championing Asciidoctor easy because I know I have a great team backing me when I get asked questions.

Wish me luck for the Asciidoctor presentation Tuesday. I'll be recording it and uploading it.

**Pull request merged**
